
#define SITE_ID_VAL  	52
#define SITE_GID_VAL 	90
#define POLARITY_DEF_VAL 0x0F 
#define ENABLE_DEFAULT 0xEF
#define TOT_MIN 5
#define LINK_TOT 0
#define DEFAULT_GAIN 32
//#define LCD_TYPE_PI 1

#define MORSEID0	MCHAR('v')
#define MORSEID1	MCHAR('e')
#define MORSEID2	2
#define MORSEID3	MCHAR('r')
#define MORSEID4	MCHAR('e')
#define MORSEID5	MCHAR('h')

#define AUXOUTOP0  AUX_OUT_FOLLOW_COR
#define AUXOUTARG0 AUX_OUT_FOLLOW_COR1 | AUX_OUT_FOLLOW_COR_INVERT1
#define AUXOUTOP1  0
#define AUXOUTARG1 0
#define AUXOUTOP2  AUX_OUT_FOLLOW_COR_DELAY
#define AUXOUTARG2 AUX_OUT_FOLLOW_COR1 | AUX_OUT_FOLLOW_COR2 | AUX_OUT_FOLLOW_COR3 | AUX_OUT_FOLLOW_COR4

// AuxIn1 used by AuxOut 1
#define AUXINOP0  AUXI_EMULATE_COR
#define AUXINARG0 AUXI_EMULATE_COR1 | AUXI_EMULATE_COR_ACTIVE_LO
#define AUXINOP1  AUXI_TAIL_WHEN_HI
#define AUXINARG1 MCHAR('b')
#define AUXINOP2  0
#define AUXINARG2 0

#define PO_AUX_OUT0 1
#define PO_AUX_OUT1 1
#define PO_AUX_OUT2 1

#define RX1_PTT 0x0E
#define RX2_PTT 0x0D
#define RX3_PTT 0x0B
#define RX4_PTT 0x07
